# NumPy Arrays

    NumPy arrays are an important in data analysis applications because they allow for the manupulation and use of arrays and tablular data.

In [2]:
import numpy as np

x1 = np.random.randint(10, size=6) # One dimesional arrays
x2 = np.random.randint(10, size=(3,4)) # Two dimensional array
x3 = np.random.randint(10, size= (3,4,5)) # Three dimensional array

Each array has arrtibutes ndim (the number of dimensions), shape (the size of each dimension), and size(the total size of the array)

In [3]:
print("x3 ndim:", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim: 3
x3 shape (3, 4, 5)
x3 size 60


In [8]:
# Three Dimensional array 
print(x3.view())

[[[5 2 1 9 8]
  [5 3 6 4 0]
  [3 4 2 9 4]
  [7 9 7 3 8]]

 [[5 1 1 4 6]
  [2 9 2 3 8]
  [8 9 1 1 3]
  [7 2 0 4 7]]

 [[2 8 7 9 4]
  [5 2 2 4 5]
  [5 7 7 3 9]
  [2 7 4 0 7]]]
[4 2 4 8 8 8]


In [9]:
# One dimensional array
print(x1.view())

[4 2 4 8 8 8]


In [11]:
# data type
print("dtpye:", x3.dtype)

dtpye: int64


Other atttributes:

* itemsize: lists the size (in bytes) of each array element

* nbytes: lists the total size (in bytes) of the of the array 

* in genearl nbytes is equal to itemsize times size

### Array Indexing 

Uses list to index array

In [19]:
for i in x1:
    print(i)

4
2
4
8
8
8


In [20]:
x1[0]

4

In [21]:
x1[4]

8

In [22]:
x1[-2]

8

In a multidimension array, items can be accessed using a comma-sepearted tuple of indicies

In [24]:
x2

array([[1, 6, 9, 1],
       [7, 9, 2, 6],
       [8, 2, 5, 0]])

In [25]:
x2[0,0]

1

In [26]:
x2[0,2]

9

Values can be modified by using index notation

In [27]:
x2[0, 0] = 12
x2

array([[12,  6,  9,  1],
       [ 7,  9,  2,  6],
       [ 8,  2,  5,  0]])

NumPy arrays have a fixed type, don't forget this

In [31]:
# pi will end up getting truncated because of the type
x1[0] = 3.14159
for i in x1:
    print(i)
    print(type(i))

3
<class 'numpy.int64'>
2
<class 'numpy.int64'>
4
<class 'numpy.int64'>
8
<class 'numpy.int64'>
8
<class 'numpy.int64'>
8
<class 'numpy.int64'>


### Array Slicing

In [34]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
print(x[:5])

[0 1 2 3 4]


In [37]:
print(x[5:])

[5 6 7 8 9]


In [38]:
print(x[4:7])

[4 5 6]


In [39]:
# print every other element

x[::2]

array([0, 2, 4, 6, 8])

In [41]:
# every other element starting at index 1

x[1::2]

array([1, 3, 5, 7, 9])

In [42]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multi Dimensional arrays 

In [43]:
print(x2)

[[12  6  9  1]
 [ 7  9  2  6]
 [ 8  2  5  0]]


In [45]:
# two rows three columns
x2[:2, :3]

array([[12,  6,  9],
       [ 7,  9,  2]])

In [47]:
#all rows every column
x2[:3, ::2]

array([[12,  9],
       [ 7,  2],
       [ 8,  5]])

In [48]:
x2_copy = x2.copy()

### Reshaping arrays 

In [51]:
# Numbers 1 through 9 in a 3x3 array
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x = np.array([1,2,3])

# row vector via reshape

x.reshape((1,3))

array([[1, 2, 3]])

In [54]:
# row vector via newaxis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [55]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [56]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### concactenatiing arrays 

In [59]:
# joining of two arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [61]:
# concatenating more than two arrays at once
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [62]:
# two dimensional arrays 
grid = np.array([[1,2,3],[4,5,6]])

In [64]:
# concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
# concatenate along the second axis
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [66]:
# it can often be clearer to use np.vstack or np.hstack

In [67]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])

# vertically stack the arrays

np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [69]:
# horizaontally stack arrays

y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [70]:
# Splitting of arrays

x = [1,2,3,99,99,3,2,1]
x1 ,x2, x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [72]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [74]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
