# Understanding how arrays are handled by python and NumPy

* Python is a dynamically typed langauge - this makes it much easier to use for data analysis than statically typed languages like C, Java or Fortran.

Basic For Loops

In [4]:
# Python code
result = 0
for i in range(100):
    result += i
    

In [2]:
print(result)

4950


Data types in python are dynamically infered and do not need to be declared.

In [6]:
# Python code

# create a integer variable 
x = 4
print(type(x))
# create a character string
x = "four"
print(type(x))

<class 'int'>
<class 'str'>


### A python integer in more than just an integer.

* Pointer to a compound C structure which contains several values.

* ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation

* ob_type, which encodes the type of the variable

* ob_size, which specifies the size of the following data members

* ob_digit, which contains the actual integer value that we expect the Python variable to represent.

### Lists, Lists, Lists
Let's consider now what happens when we use a Python data structure that holds many Python objects. The standard mutable multi-element container in Python is the __list__. We can create a list of integers as follows:

In [11]:
# list of Integers
L = list(range(10))
print(L)
print(type(L[0]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'int'>


In [13]:
# list of strings
L2 = [str(c) for c in L]
L2
print(L2)
print(type(L2[0]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'str'>


In [14]:
# list of many types
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

List flexibility comes ar a cost: to allows these flexible types, each tiem in the list must contain:

* It's own type info

* Reference info

* Other info, each item in list it's own python object.

### Fixed type Arrays

In [16]:
# Python Array 

import array
L = list(range(10))
# 'i' is a type code tellling us that the array contains integers
A = array.array('i', L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
# NumPy array
import numpy as np 
# integer array
print(np.array([1,4,2,5,3]))

[1 4 2 5 3]


Note: arrays must have items of al the same type.  For example in the two scenarios above we had integer arrays

In [19]:
# Funky Integer Float array 

np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [20]:
# Set the data type of resulting array

np.array([1,2,3,4], dtype = 'float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [21]:
# Arrays can also be multi-dimensional:

np.array([range(i, i +3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

* Large arrays are much easier to simulate than type

In [23]:
# Length-10 array with all zeros

np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# 3x5 floating point filled with ones

np.ones((3,5), dtype =float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [26]:
# 3x5 array filled with 3.14

np.full((3,5), 3.14)


array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [27]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [29]:
# Create a 3x3 array of normally distributed ransom values with mean 0 and sd 1
np.random.normal(0, 1, (3,3))

array([[ 0.43792302,  0.06793742, -0.64720062],
       [-0.90185708,  1.39566231, -0.09898672],
       [ 0.06199128, -0.46798243,  0.18993909]])

In [30]:
# Create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0, 10, (3,3))

array([[4, 9, 7],
       [4, 2, 3],
       [0, 2, 2]])

In [31]:
# Create a 3x3 identity matrix

np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
# Create an inititialized aeeay of three intergers 
# The values will be whatever happens to already exist at that moeory
np.empty(3)

array([ 1.,  1.,  1.])

### NumPy data types


*Data type	Description

*bool_	Boolean (True or False) stored as a byte

*int_	Default integer type (same as C long; normally either int64 or int32)

*intc	Identical to C int (normally int32 or int64)

*intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)

*int8	Byte (-128 to 127)

*int16	Integer (-32768 to 32767)

*int32	Integer (-2147483648 to 2147483647)

*int64	Integer (-9223372036854775808 to 9223372036854775807)

*uint8	Unsigned integer (0 to 255)

*uint16	Unsigned integer (0 to 65535)

*uint32	Unsigned integer (0 to 4294967295)

*uint64	Unsigned integer (0 to 18446744073709551615)

*float_	Shorthand for float64.
*float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
*float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
*float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
*complex_	Shorthand for complex128.
*complex64	Complex number, represented by two 32-bit floats
*complex128	Complex number, represented by two 64-bit floats